### ISSUE TITLE
Inquiry on code and dataset release

### ISSUE THREAD

**Issue by hayleyson** [msantoshmadhav/LogicAttack#1]
Dear team, 

First of all, congratulations and thank you for your fantastic work! I am curious if you have plans to release your code and dataset through this repository.

Cheers,
Hayley Son

**Comment by Mihir3009** [comment]
We will upload it soon. Thanks for your patience!

**Comment by Mihir3009** [comment]
Hello @hayleyson,

We have updated the data. Please let us know if you need more details on it.
